# Generated by Django 2.1 on 2018-08-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_coupon_couponrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
    ]
