# Generated by Django 2.1 on 2018-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180814_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '账户'},
        ),
    ]
